# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'DrawerDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic 
#frameworks
  use_frameworks!

  # Pods for DrawerDemo
pod 'MMDrawerController', '~> 0.6.0'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'IQKeyboardManager', '~> 4.0.4'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'Charts', '~> 2.2.5'
end

