# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'DrawerDemo' do
pod 'MMDrawerController', '~> 0.6.0'
pod 'FDFullscreenPopGesture', '~> 1.1'
end

